// animalInventoryTypes.js
export const GET_ANIMAL_INVENTORY_REQUEST = 'GET_ANIMAL_INVENTORY_REQUEST';
export const GET_ANIMAL_INVENTORY_SUCCESS = 'GET_ANIMAL_INVENTORY_SUCCESS';
export const GET_ANIMAL_INVENTORY_FAIL = 'GET_ANIMAL_INVENTORY_FAIL';
