// actionTypes.js

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const TOGGLE_CART_ITEM_SELECTION = 'TOGGLE_CART_ITEM_SELECTION';
export const TOGGLE_BULK_SELECTION = 'TOGGLE_BULK_SELECTION';
export const INCREMENT_ITEM_QUANTITY = 'INCREMENT_ITEM_QUANTITY';
export const DECREMENT_ITEM_QUANTITY = 'DECREMENT_ITEM_QUANTITY';