// ordertypes.js

export const INSTALLATION_PAYNOW_REQUEST = 'INSTALLATION_PAYNOW_REQUEST';
export const INSTALLATION_PAYNOW_SUCCESS = 'INSTALLATION_PAYNOW_SUCCESS';
export const INSTALLATION_PAYNOW_FAIL = 'INSTALLATION_PAYNOW_FAIL';
