export const GET_MASTER_PACKAGES_REQUEST = 'GET_MASTER_PACKAGES_REQUEST';
export const GET_MASTER_PACKAGES_SUCCESS = 'GET_MASTER_PACKAGES_SUCCESS';
export const GET_MASTER_PACKAGES_FAIL = 'GET_MASTER_PACKAGES_FAIL';
