export const ADD_PARTICIPANTS_REQUEST = 'ADD_PARTICIPANTS_REQUEST';
export const ADD_PARTICIPANTS_SUCCESS = 'ADD_PARTICIPANTS_SUCCESS';
export const ADD_PARTICIPANTS_FAIL = 'ADD_PARTICIPANTS_FAIL';
export const ADD_EMPTY_PARTICIPANTS = 'ADD_EMPTY_PARTICIPANTS';
