// // signUpTypes.js

export const SIGNUP_ORDER_REQUEST = 'SIGNUP_ORDER_REQUEST';
export const SIGNUP_ORDER_SUCCESS = 'SIGNUP_ORDER_SUCCESS';
export const SIGNUP_ORDER_FAIL = 'SIGNUP_ORDER_FAIL';
export const SIGNUP_ORDER_RESET = 'SIGNUP_ORDER_RESET';