// transactionsByidtypes.js

export const GET_TRANSACTIONS_BY_ID_REQUEST = 'GET_TRANSACTIONS_BY_ID_REQUEST';
export const GET_TRANSACTIONS_BY_ID_SUCCESS = 'GET_TRANSACTIONS_BY_ID_SUCCESS';
export const GET_TRANSACTIONS_BY_ID_FAIL = 'GET_TRANSACTIONS_BY_ID_FAIL';
